### ISSUE TITLE
Cursor jumps to end of textfield when typing anywhere but the end.

### ISSUE THREAD

**Issue by feep** [qri-io/desktop#483] opened 2020-03-16 13:43 UTC
0.4.0 Mac

When typing in the middle of a text field (bug present in __Commit > Title__ and __Commit > Message__) first character types at the cursor, the next character the cursor jumps to the end of the input.

**Comment by chriswhong** [comment] 2020-09-22 16:09
Dupe of #496

**Closed by chriswhong** 2020-09-22 16:09 UTC
Labels: bug
