### ISSUE TITLE
Cannot publish a dataset that has already been published via CLI

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/desktop#304] opened 2019-10-23 20:47 UTC
I have a dataset I created and published via the CLI (v0.9.0). (`mr0grog/edgi_webmonitoring_changed_terms_top`)

When I open it in Desktop (v0.1.0-rc1), save a change to the title, and click the publish button, I get an error:

> 500 pq: duplicate key violates unique constraint "dataset_refs_pkey"

<img width="512" alt="Screen Shot 2019-10-23 at 1 33 19 PM" src="https://user-images.githubusercontent.com/74178/67432390-0ee2ee80-f59b-11e9-9212-17371a5a9e57.png">

After refreshing the UI, I tried again and got a different error:

> 400 this dataset has already been published

<img width="509" alt="Screen Shot 2019-10-23 at 1 39 54 PM" src="https://user-images.githubusercontent.com/74178/67432451-27530900-f59b-11e9-88e1-d2af369141e1.png">

…but the dataset on qri.cloud definitely does not have my latest commit: https://qri.cloud/mr0grog/edgi_webmonitoring_changed_terms_top

![Screen Shot 2019-10-23 at 1 45 07 PM](https://user-images.githubusercontent.com/74178/67432591-5b2e2e80-f59b-11e9-9d26-fc60dd598fa3.png)

Trying to publish from the CLI `qri publish` returns immediately with no output and also does not seem to update on qri.cloud.

**Comment by Mr0grog** [comment] 2019-10-23 20:51
Uhoh, just looked at my profile page on qri.cloud and I have the same dataset twice now (each at a different version):

![Screen Shot 2019-10-23 at 1 51 07 PM](https://user-images.githubusercontent.com/74178/67432988-2f5f7880-f59c-11e9-83b2-ff1d5b877450.png)

**Comment by ramfox** [comment] 2019-10-24 14:02
@Mr0grog going to investigate this

Do you know if, when you created the first dataset, if you used `qri init` to create it, or did you immediately `qri save`?

**Comment by Mr0grog** [comment] 2019-10-24 16:16
> Do you know if, when you created the first dataset, if you used `qri init` to create it, or did you immediately `qri save`?
> …
> Okay, this actually errors when you publish, save, and publish again all from the CLI, or if you do the same steps all from the desktop.

Yep, this squares with what I remember doing. `qri init` then `qri save` then `qri publish` all on CLI before switching to desktop (where I saved a second commit and then tried to publish).

> btw, if you want to clean up your profile, `qri log` and `qri publish --unpublish me/my_dataset@/ipfs/each_version_hash` is your best friend!

Oooh, thank you!

**Comment by chriswhong** [comment] 2020-01-24 15:41
Closing, it looks like the cloud issue was closed, and I couldn't reproduce.   Please re-open if it's still happening.

**Closed by chriswhong** 2020-01-24 15:41 UTC
Labels: bug
