### ISSUE TITLE
I can only see/work on 1 dataset at a time

### ISSUE THREAD

**Issue by amandabNYC** [qri-io/desktop#356] opened 2019-12-03 04:32 UTC
I cannot see the history of datasets I've created in Qri - I can only see in the most current dataset I've worked on the the status bar.
<img width="528" alt="Qri4" src="https://user-images.githubusercontent.com/41880533/70020754-f253b200-155b-11ea-8108-55568594b96e.png">
<img width="151" alt="Qri5" src="https://user-images.githubusercontent.com/41880533/70020756-f4b60c00-155b-11ea-81ca-16f7c7b76a85.png">

**Comment by chriswhong** [comment] 2019-12-04 20:36
Can you tell me what you see when you type `qri list` in a command prompt?

**Comment by dustmop** [comment] 2019-12-06 21:40
Hi @amandabNYC, sorry for the delay in responding to this issue. I'm going to be taking a look at this early next week to try and help you out.

This is running on Windows, right? When you get a chance, could you open the app and do the following:
1. press the keyboard shortcut "Ctrl+Shift+I (capital i)" to open Developer Tools
2. click the "Console" tab
3. screenshot or copy-paste the contents into this issue

That would help us diagnostic what the issue is that's causing Qri Desktop to not work correctly.

Here's an example of what this looks like on my machine:
![qri_example_win](https://user-images.githubusercontent.com/2515490/70358313-13abeb00-1847-11ea-8d9e-5f9a79ae46e9.PNG)

**Comment by amandabNYC** [comment] 2019-12-09 23:10
I don't have command prompt access - I am working from a PC. I don't know
if that makes a difference.

**Comment by amandabNYC** [comment] 2019-12-09 23:13
See attached for screenshot:

**Comment by ramfox** [comment] 2019-12-12 16:22
hi @amandabNYC ! I think when you replied to the email, the screenshot was lost. Mind heading over to https://github.com/qri-io/desktop/issues/356 and posting the screenshot again :)

**Comment by dustmop** [comment] 2019-12-12 21:08
I watched the video from the recent meeting where this came up. It helped a bunch! Here's what I got from it:

1) Was able to figure out the cause of the "Oops, something went wrong with this commit" message. Our backend requires that dataset names start with a letter, so the name "911calls" won't work. We have to make sure that our rules about what dataset names are valid are consistent, and desktop needs to be both checking the dataset name and also handling errors better.

2) But something was going wrong with Desktop even before that. When @amandabNYC clicked on "Create Dataset" in the "Create a New Dataset" dialog box, the app makes a call to "/init", and waits for it to return, but afterwards the dialog box doesn't close. What's weird is that it didn't get an error. This seems to be the root of the other problems, including the right-hand pane showing multiple views at once.

3) I could theorize about what's going wrong here, but we really need better logging for desktop to gather data about what part specifically is breaking. We're probably not handling some error somewhere. Would be cool if a user could click a "download log" button somewhere that would save a logfile that could then be emailed to us.

4) Our recent UI redesign is going to remove this flow, meaning it may not even be possible to recreate going forward. Whatever this specific error case was, it might just disappear.

**Comment by amandabNYC** [comment] 2019-12-13 18:45
<img width="415" alt="Qri6" src="https://user-images.githubusercontent.com/41880533/70823756-ac45ec00-1dae-11ea-88d7-025c7958a1ce.PNG">
 I'm not sure if this is still relevant or not, but see attached.

 I haven't had a chance to use the updated version as of yet. I will apprise of any new/continuing issues once I'm back on wi-fi.

**Comment by chriswhong** [comment] 2020-01-24 15:59
I believe these should be addressed in newer releases.  Please re-open if you're still seeing the issue.

**Closed by chriswhong** 2020-01-24 15:59 UTC
