### ISSUE TITLE
Lost ability to drag windows.

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/desktop#539] opened 2020-04-27 18:06 UTC
+ I work on a laptop and there is a strange issue where if the Qri application window is reduced vertically to be as small as possible, you lose the ability to drag the windows by clicking on the top bar. It isn't until you stretch the window to the left or right that it comes back.

(from a qri desktop user)

**Comment by uhLeeshUh** [comment] 2020-09-10 18:32
@rgardaphe I see this was a comment from a desktop user - do you remember who they were so I can reach out? I just tried to reproduce the issue and I'm not seeing the issue.

For context, to reproduce I:
- ran the latest version of Desktop in production mode
- dragged the edges of the app to the smallest size possible (both vertically and horizontally)

and I'm still able to drag the window around by clicking on the top bar. I've added a screenshot of what my app looks like to show the relative size of what I was able to get it down to

<img width="1176" alt="Screen Shot 2020-09-10 at 11 29 36 AM" src="https://user-images.githubusercontent.com/31083146/92781691-354b7d00-f359-11ea-9791-1f046c65b5af.png">

**Comment by b5** [comment] 2020-10-06 00:38
I think we've fixed this, and it'll be "even more fixed" when we switch to the new layout in an upcoming release, which has more draggable area in the header. closing

**Closed by b5** 2020-10-06 00:38 UTC
Labels: UX, ui
