### ISSUE TITLE
Reloading desktop after removing dataset 

### ISSUE THREAD

**Issue by astroland** [qri-io/desktop#126] opened 2019-08-29 18:42 UTC
after removing a dataset from your local collection, there is a need to reload the screen in order to navigate to another feature of the desktop app. in other words, the screen goes blank white when attempting to navigate to another feature of the desktop app prior to reloading

**Comment by b5** [comment] 2019-08-29 19:10
Ah yes we should definitely address this. I think the issue is a dataset that gets deleted can still be "selected" in desktop, which causes the all-white flash.


But first: you've got the new desktop app compiled & running!? Awesome!
What steps are you taking to build? Are you running Qri from the command line?

As an example, I've been running `yarn dev` in one terminal and `qri connect` in another.

**Comment by astroland** [comment] 2019-08-30 20:47
I am running Qri from the command line. I actually have a question about building ..I am going to post a question on discord for further help

**Comment by chriswhong** [comment] 2019-10-01 14:51
Dataset removal should be a-ok in desktop v0.1.0.  Closing

**Closed by chriswhong** 2019-10-01 14:51 UTC
Labels: bug
